export const BASE_URL = import.meta.env.VITE_API_BASE_URL;

export const GET_APIS = {
  get_all_companies: `${BASE_URL}admin/get_companies`,
  get_all_company_admins: `${BASE_URL}admin/get_all_company_admins`,
  company_code_dropdown: `${BASE_URL}admin/company_code_dropdown`,
  country_list: `${BASE_URL}/get_country_options`,
  getSEOlist:`${BASE_URL}admin/get_seo_list`,
  getSEObyPath:`${BASE_URL}admin/get_seo_by_path`,

};

export const POST_APIS = {
  login: `${BASE_URL}company/login`,
  // fileUpload: `${BASE_URL}upload_files`,
  fileUpload: `${BASE_URL}upload_files_new`,
  tracker: `${BASE_URL}get_file_status`,
  chat_ai: `${BASE_URL}chat_ai`,
  execute_sql: `${BASE_URL}execute_sql`,
  // get_ui_data: `${BASE_URL}get_ui_data`,
  processSessionData: `${BASE_URL}process_session_data`,
  get_dashboard_data: `${BASE_URL}get_dashboard_data`,
  save_chat: `${BASE_URL}query_save`,
  // get_chat_history: `${BASE_URL}get_uploaded_table_with_tabledata`,
  get_table_data: `${BASE_URL}get_full_table_info`,
  get_saved_query_response: `${BASE_URL}get_saved_query_response`,
  get_report_list: `${BASE_URL}report_list`,
  report_save: `${BASE_URL}report_save`,
  delete_uploaded_file: `${BASE_URL}delete_uploaded_file`,
  upload_progress: `${BASE_URL}get_upload_progress`,
  super_admin_login: `${BASE_URL}superadmin/login`,
  admin_company_delete: `${BASE_URL}admin/company_delete`,
  modify_chart: `${BASE_URL}modify_chart`,
  company_register: `${BASE_URL}admin/company_register`,
  company_admin_register: `${BASE_URL}admin/company/admin_register`,
  company_get_users: `${BASE_URL}/admin/company_get_users`,
  company_user_register: `${BASE_URL}company_user_register`,
  contact_us: `${BASE_URL}contact`,
  logo : `${BASE_URL}admin/company/logo`,
  createSEO:`${BASE_URL}admin/create_seo`,
  updateSEO:`${BASE_URL}admin/update_seo`,
  deleteSEO:`${BASE_URL}admin/delete_seo`,
  generate_pdf:`${BASE_URL}generate_pdf`,
  address_book_list:`${BASE_URL}address_book_list`,
  address_book_create:`${BASE_URL}address_book_create`,
  address_book_email_add:`${BASE_URL}address_book_email_add`,
  address_book_email_remove:`${BASE_URL}address_book_email_remove`,
  reports_dropdown:`${BASE_URL}reports_dropdown`,
  report_schedules_list:`${BASE_URL}report_schedules_list`,
  save_report_scheduler:`${BASE_URL}save_report_scheduler`
};